# blacklist:
# List of blocks that cannot be used to create a SecretDoor or Secret Trapdoor
# whitelist:
# To use the whitelist change enable-whitelist to true
# This setting is disabled by default - it overrides the blacklist and allows for ONLY these blocks to be used as SecretDoors
# List of blocks that can be used as SecretDoors, iff enable-whitelist is true
# Be sure to add the correct fields here - for instance, add SNOW_BLOCK, not SNOW
# Materials reference: http://jd.bukkit.org/beta/apidocs/org/bukkit/Material.html
use-permissions: true
enable-redstone: true
enable-trapdoors: true
enable-timers: false
enable-whitelist: false
close-time-seconds: 5
vaild-doortypes:
  - OAK_DOOR
  - ACACIA_DOOR
  - BIRCH_DOOR
  - DARK_OAK_DOOR
  - JUNGLE_DOOR
  - SPRUCE_DOOR
  - CRIMSON_DOOR
  - WARPED_DOOR
  - BAMBOO_DOOR
  - CHERRY_DOOR
  - PALE_OAK_DOOR
  - MANGROVE_DOOR
  - COPPER_DOOR
  - EXPOSED_COPPER_DOOR
  - WEATHERED_COPPER_DOOR
  - OXIDIZED_COPPER_DOOR
  - WAXED_COPPER_DOOR
  - WAXED_EXPOSED_COPPER_DOOR
  - WAXED_WEATHERED_COPPER_DOOR
  - WAXED_OXIDIZED_COPPER_DOOR
vaild-trapdoortypes:
  - OAK_TRAPDOOR
  - ACACIA_TRAPDOOR
  - BIRCH_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  - BAMBOO_TRAPDOOR
  - COPPER_TRAPDOOR
  - CHERRY_TRAPDOOR
  - PALE_OAK_TRAPDOOR
  - MANGROVE_TRAPDOOR
  - EXPOSED_COPPER_TRAPDOOR
  - WEATHERED_COPPER_TRAPDOOR
  - OXIDIZED_COPPER_TRAPDOOR
  - WAXED_COPPER_TRAPDOOR
  - WAXED_EXPOSED_COPPER_TRAPDOOR
  - WAXED_WEATHERED_COPPER_TRAPDOOR
  - WAXED_OXIDIZED_COPPER_TRAPDOOR
blacklist:
  - DISPENSER
  - CHEST
  - WORKBENCH
  - FURNACE
  - BURNING_FURNACE
  - STONE_PLATE
  - WOOD_PLATE
  - REDSTONE
  - REDSTONE_WIRE
  - REDSTONE_TORCH_ON
  - REDSTONE_TORCH_OFF
  - WOODEN_DOOR
  - IRON_DOOR
  - IRON_DOOR_BLOCK
whitelist:
  - STONE
  - COBBLESTONE
  - WOOD
